### ISSUE TITLE
How to unhide app bar?

### ISSUE THREAD

**Issue by gmcouto** [92lleo/WhatsappWebToGo#106]
Thanks for this marvelous app...

I think I have hidden the app bar... and do not know how to unhide it... How?

**Comment by 92lleo** [comment]
Hi @gmcouto 
as you already closed it - found out yourself?
I agree it's a bit tricky. Pull from the left to get the side menu open. if you have gesture control, press and hold on the left edge, then pull in once the side bar appears.
