### ISSUE TITLE
Whatsapp only works with Chrome 49

### ISSUE THREAD

**Issue by 92lleo** [92lleo/WhatsappWebToGo#12]
![image](https://user-images.githubusercontent.com/12110344/60543703-3fb2c580-9d17-11e9-932b-e56f30b12ce4.png)

Whatsapp Web won't load but will show this warning.

Will be resolved Wednesday evening

**Comment by 92lleo** [comment]
Fixed in [1.4.0](https://github.com/92lleo/WhatsappWebToGo/releases/tag/v1.4.0)

**Comment by lisianeschwantesmachado180901** [comment]
Hello Leo, did you solve it? Will we have to download a new version of the app? Do you send the link? Waiting for answer, thank you!

**Comment by 92lleo** [comment]
Hi, please check the releases, there is a version 1.4.0. 
This version is also linked in the comment above.

**Comment by ristein** [comment]
hey, great wortk 👍 
could you unpinn this issue?
I guess its not needed anymore

**Comment by 92lleo** [comment]
correct, thanks for reminding!
