### ISSUE TITLE
Keyboad disables on app start

### ISSUE THREAD

**Issue by Jamesa87** [92lleo/WhatsappWebToGo#120]
Hi, I have a Samsung SM-A520F. Whenever I open this application I see a banner at the bottom of my screen that says "keyboard disabled".

I can't seem to find where to enable it?

**Comment by 92lleo** [comment]
top right is a keyboard icon. It's used for reading chats easier without the keyboard popping up everytime a chat is opened. the keyboard icon in the top right corner enabels/disables it.
