### ISSUE TITLE
Is there is a way to run whatsappWebToGo on old devices, like android 4.4.4?

### ISSUE THREAD

**Issue by Antwa-sensei253** [92lleo/WhatsappWebToGo#121]

**Comment by 92lleo** [comment]
Android Web view is bundled into 4.4 and not updated trough the store, it's to old to run whatsapp web. -> not supported.
To bring this app to 4.4, a webview need to be bundled in the apk and updated separately which would result in a way bigger apk which has to be maintained separately. Marked share for devices below Anrdoid 7.0 is <3% -> won't do.

**Comment by Antwa-sensei253** [comment]
Thanks for the Information 92lleo
