### ISSUE TITLE
No builds apart of Android Q

### ISSUE THREAD

**Issue by BlueGuitarCL** [92lleo/WhatsappWebToGo#14]
Currently i have a Xiaomi Redmi 3 running on Android 5.1.1 and i got ver. 1.0.1 running but with the white screen bug. Got here thanks the github link, but none of the releases prior to that version works to me. The Play Store site is down, and there're no readme for building the app by myself (idk enough :c)

Until which version you're planning to support on your app?

**Comment by 92lleo** [comment]
Hi, have you tried the release 1.4.0? It's build with the q sdk but supports back to sdk 21 (5.0), so 5.1 should work

**Comment by beppe9000** [comment]
hello did you test this with memu player? stays like this forever, saying not compatible.
![image](https://user-images.githubusercontent.com/6625123/77095831-b95a2300-6a0e-11ea-9545-6953cf64e7a2.png)
