### ISSUE TITLE
Add fastlane file structure

### ISSUE THREAD

**Issue by 92lleo** [92lleo/WhatsappWebToGo#15]
Add fastline file structure as detailed in [fdroid doc](https://gitlab.com/snippets/1895688)
(task from #8)

- [x] Create screenshots for phone and tabled (the old screenshots don't look very good)
- [x] Create App summary and description
- [x] tag and release

**Comment by 92lleo** [comment]
Added with 7ce775b
leaving issue open until store entry is live

**Comment by PanderMusubi** [comment]
The metadata is looking good. Instead of fastlane in the top-level, also metadata in the top-level is possible but depends on you and your usage of fastlane in other strores than F-droid.

Nice would be also add a feature graphic, here is a royalty-free suggestion:

![featureGraphic](https://user-images.githubusercontent.com/198964/76757165-6a4e8c80-6787-11ea-996d-acad65c26543.png)

**Comment by 92lleo** [comment]
Thanks for the suggestion! I just took it as is - maybe I have more motivation to do something else later:) 
For the file structure: Currently I'm only releasing on fdroid (once the builds start working), so it doesn't really matter

**Comment by 92lleo** [comment]
@PanderMusubi as the store entry is now live (https://f-droid.org/packages/io.kuenzler.whatsappwebtogo/), how do I get it to use "my" metadata?

**Comment by PanderMusubi** [comment]
If you move metadata one directory up and remove fastlane it should appear in next release. @IzzySoft correct?

**Comment by IzzySoft** [comment]
I wouldn't recommend that (though it should indeed work). Instead, switch to the proper [Fastlane file structure](https://gitlab.com/snippets/1895688): there's one directory level missing here. This repo has `fastlane/metadata/en-US/*` – correct would be `fastlane/metadata/android/en-US`.

**Comment by 92lleo** [comment]
@IzzySoft next release is out (took a while..). Changelog and Images worked, but Title and Description not so much. Anything I still need to do?
https://f-droid.org/en/packages/io.kuenzler.whatsappwebtogo/

**Comment by IzzySoft** [comment]
Yes, we'd need to open another MR at F-Droid to remove the local description. But first you'd need to fix your fastlane short-description: max 80 chars are permitted, all behind that will get truncated. Yours has 129 chars, so almost half of that will be cut off. I'd simply make that

    access WhatsApp Web on your mobile device - send audio, pictures and video

Then, after you've tagged your next release (fastlane is always tied to that), we can go and switch over. While on it, why not taking some of the current description into your `full_description.txt`? Combining both, that could be something like:

```html
<i>WhatsappWeb</i> lets you access WhatsApp Web on your mobile phone or tablet. It has full support for sending audio and pictures / video. With a clean and easy interface it's fun to use - it even shows up as running on an Android phone on the phone where WhatsApp is installed!

-free and without ads-

If you have problems just send a mail or create a github issue.

This app is in no way affiliated with WhatsApp Inc. The rights for WhatsApp and WhatsApp Web belong to WhatsApp Inc. This app is a private project to enable the use of WhatsApp Web on Android Devices.
```

**Comment by 92lleo** [comment]
Thanks for the quick feedback and tips! I updated short-description and description. I want to wait for an actual change to the app for the next tagged release to avoid having "empty" releases. 
I'll ping here again once it's done

**Comment by 92lleo** [comment]
Release was picked up by fdroid: https://f-droid.org/wiki/page/io.kuenzler.whatsappwebtogo/lastbuild_30

**Comment by 92lleo** [comment]
@IzzySoft  ping :)
change is now picked up by buildserver and store -> https://f-droid.org/en/packages/io.kuenzler.whatsappwebtogo/

**Comment by IzzySoft** [comment]
@92lleo pong, [here you go](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7076) :smiley:

**Comment by IzzySoft** [comment]
@92lleo as for pulling from fastlane, I had to clear all summaries as well. You might wish to add the corresponding `short_description.txt` files to your fastlane:

* **pl:** "Klient internetowy WhatsApp dla twojego telefonu/tabletu z obsługą multimediów"
* **tr:** "Medya desteği olan telefonunuz/tabletiniz için WhatsApp Web istemcisi"
* **zh-CN:** "适用于您的手机/平板电脑的 WhatsApp 网页客户端，具有媒体支持"

**Comment by 92lleo** [comment]
@IzzySoft I'm preparing a release currently, is there anything needed to be included (besides the short descriptions)?

**Comment by PanderMusubi** [comment]
The feature graphic

**Comment by IzzySoft** [comment]
Looks like your fastlane structure contains everything that's needed (short and full desc), what's recommended (screenshots, changelogs), what's nice-to-have (featureGraphic), and even more (title). Now you'd only need to get some things in the right place: all the picture stuff needs to be below `fastlane/metadata/android/<locale>/images` (see [my snippet](https://gitlab.com/snippets/1895688) for orientation). So you'd need to create the `images` directory where currently your descriptions reside, and then move the featureGraphic plus the phoneScreenshots directories inside that. You could also add an `icon.png` inside that `images` directory – though as you still use PNG icons (and not XML), that's not "urgently required".

**Comment by 92lleo** [comment]
@IzzySoft thanks for the hint, I somehow overlooked the image dir. Fixed now.
@PanderMusubi Your suggested feature graphic was added earlier, should be in the right dir now, too. Thanks!

If the metadata looks good for you now, I'd tag a new release

**Comment by IzzySoft** [comment]
Yes, looks good now! When tagged, please send a note to the corresponding RFP (or update the MR, whichever it is). Thanks!

**Comment by 92lleo** [comment]
Tagged as [v1.6.2](https://github.com/92lleo/WhatsappWebToGo/releases/tag/v1.6.2). 
Do you mean the [initial RFP](https://gitlab.com/fdroid/rfp/-/issues/1123)?

**Comment by IzzySoft** [comment]
Oops, no – I see your app was already added. Then we'd need a MR to remove summary/description from our metadata, so fastlane can take over.

**Comment by 92lleo** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7076?commit_id=551b21681a61bb2a7c2b901867714bb94e2a21f0
already done by you 😀 so everything should be ready? Build for 31 went trough, store didn't pick it up yet.

**Comment by IzzySoft** [comment]
Ah, I did that already… well, so much work, one doesn't remember each single item :rofl:

Yes, then everything should be ready. I didn't check when that build went through – but of course it would need to be signed (manual step) and then won't appear before the next index is published.

**Comment by Domi04151309** [comment]
Fastlane file structure is present and working. I think this can get closed?

**Comment by 92lleo** [comment]
Correct. Thank you all for your help! Closing.
