### ISSUE TITLE
Unable to setup after installing.

### ISSUE THREAD

**Issue by marcosimonegili** [92lleo/WhatsappWebToGo#16]
Sorry, something went wrong.
We're working on getting this fixed as soon as we can.

![Screenshot_20200313-185736](https://user-images.githubusercontent.com/29420400/76647351-f4ff7380-655c-11ea-8484-bd31940c2e7e.png)

WAWTG version: 1.5.2
Device: Fire HD 8 (8th gen)
OS: Fire OS 6.3.1.5 (based on Android 7.1 Nougat)

**Comment by 92lleo** [comment]
Hi,
I didn't see this issue before, I'll look into it. Until then, please try older app versions until 1.4.0 and see, if any of those work. 
It could be possible that FireOS is shipping an old or stripped down version of android webview. I'll test some possibilites and report back here

**Comment by marcosimonegili** [comment]
> Hi,
> I didn't see this issue before, I'll look into it. Until then, please try older app versions until 1.4.0 and see, if any of those work.
> It could be possible that FireOS is shipping an old or stripped down version of android webview. I'll test some possibilites and report back here

Indeed 1.4.0 works!
![Screenshot_20200315-115915](https://user-images.githubusercontent.com/29420400/76700133-ba105380-66b4-11ea-8d97-4117453434e0.png)

**Comment by 92lleo** [comment]
Perfect, I'll check for any affecting changes and try to fix it

**Comment by 92lleo** [comment]
Seems like whatsapp is checking features according to the given UA. I was able to reproduce the issue mentioned above in WhatsappWebToGo when trying with an older device. The UA I've currently set in the app is the current chrome UA. I changed it to the current Firefox UA and the issue is gone.

After changing the UA to an older chrome version (75 instead of 79) the issue is gone on my test device.

@marcosimonegili  could you please test the attached apk?
[wawtg_28_test.zip](https://github.com/92lleo/WhatsappWebToGo/files/4345295/wawtg_28_test.zip)

**Comment by marcosimonegili** [comment]
> Seems like whatsapp is checking features according to the given UA. I was able to reproduce the issue mentioned above in WhatsappWebToGo when trying with an older device. The UA I've currently set in the app is the current chrome UA. I changed it to the current Firefox UA and the issue is gone.
> 
> After changing the UA to an older chrome version (75 instead of 79) the issue is gone on my test device.
> 
> @marcosimonegili could you please test the attached apk?
> [wawtg_28_test.zip](https://github.com/92lleo/WhatsappWebToGo/files/4345295/wawtg_28_test.zip)

The test version loads correctly!!

![Screenshot_20200317-201615~2](https://user-images.githubusercontent.com/29420400/76893469-b0414880-688c-11ea-85d4-c89b38cbba33.png)

**Comment by 92lleo** [comment]
Perfect, thanks for the quick response! I'll release a new version, you can keep the test version installed.

**Comment by marcosimonegili** [comment]
So, now I Just keep the test version, or should I install the major release? Sorry to bother you 🙂

**Comment by 92lleo** [comment]
No problem:) Easiest is to keep the test version, once something newer than 1.5.3 releases, you can update as usual.
