### ISSUE TITLE
Does not install on memu player

### ISSUE THREAD

**Issue by 92lleo** [92lleo/WhatsappWebToGo#17]
From @beppe9000:

> hello did you test this with memu player? stays like this forever, saying not compatible.
> ![image](https://user-images.githubusercontent.com/12110344/77096187-42715a00-6a0f-11ea-9464-c8659438534f.png)
>

**Comment by 92lleo** [comment]
Hi @beppe9000,
i did not test it with memu player, but it should install on every android instance without issues. Did you have these issues before?

**Comment by 92lleo** [comment]
@beppe9000 ping

**Comment by beppe9000** [comment]
in the end i installed on a physical device
