### ISSUE TITLE
Please rename (un)hide Navbar to (un)hide Appbar

### ISSUE THREAD

**Issue by ort163** [92lleo/WhatsappWebToGo#18]
Please rename (un)hide Navbar to (un)hide Appbar

If you these pages:
App bar:
https://developer.android.com/training/appbar/

Nav bar is the one on the bottom
https://material.io/design/platform-guidance/android-bars.html#android-navigation-bar

**Comment by 92lleo** [comment]
Thanks for the hint, will be fixed in next release
