### ISSUE TITLE
Downloading media not working

### ISSUE THREAD

**Issue by naveenjohnsonv** [92lleo/WhatsappWebToGo#19]
Shows that the media has been downloaded but unable to locate it on the device. Tried even after manually providing storage permission.

**Comment by 92lleo** [comment]
Hi,
downloading media from whatsapp web is not supported by the current webview. I have a few ideas on how to solve this, but no time to do it yet

**Comment by naveenjohnsonv** [comment]
No problem :)

**Comment by 92lleo** [comment]
Found a way. If everything works out, it will be included in the next release :)

**Comment by naveenjohnsonv** [comment]
That's great. Eagerly waiting!

**Comment by SaahibJee** [comment]
> Found a way. If everything works out, it will be included in the next release :)

Where is the update ?
Have you found it

**Comment by 92lleo** [comment]
Unfortunately there is no update yet.
It involves more work than expected an currently I don't have the time to dig into it. It's still on the todo list though.

**Comment by firebrain12** [comment]
Fixed!!!

**Comment by 92lleo** [comment]
Currently the download is being triggered twice. Once this is fixed, I'll release the new version

**Comment by firebrain12** [comment]
Ok 👌 I will have a look at it as well  thanks for your understanding 😁

BR
The Genius

**Comment by firebrain12** [comment]
Hey at the moment am working on a way to get notification working in the
project but I would like to no if sending you the counter appeal for the
DMCA claim is a good idea or is there a other way to get my apps back and
running soon as day come back online it will be taken down and  updated
with your credentials please let me know am not trying to get my self in
any lawsuit against you honestly i just want to be fear it's not about the
money but the strikes against my account I understand that you were very
upset with me hope you see that am not a bad person i  just had lack of
knowledge towards these licenses is there another way to get this done or
do I have to send the appeal ? am literally waiting on your response please
here my cry  please reply ;(

BR
Markie

**Comment by 92lleo** [comment]
@all Please check the new release 1.7.0
For newer android versions the permission is broken. If you can't download files, set the storage permission manually for the app. I'll fix this asap!

**Comment by firebrain12** [comment]
Yup that's why I had added it for you the first time👌

**Comment by 92lleo** [comment]
I kept the permission, I just moved it to the right places, so it does only ask when you really need it. Besides that, the logic is working until Android 10 (included). For 11 it's broken as the permission scheme changed. I'll work on that

**Comment by 92lleo** [comment]
Workaround for missing permission request on android 11 is live with [Release 1.7.1](https://github.com/92lleo/WhatsappWebToGo/releases/tag/v1.7.1).
Fixing permission requests for Android 11 is further tracked in #46 
-> Closing
