### ISSUE TITLE
How not to block keyboard 

### ISSUE THREAD

**Issue by void00r** [92lleo/WhatsappWebToGo#27]
It dont let keyboard to to access the app

**Comment by 92lleo** [comment]
Hi,
I don't know if I understand correctly. You want to unblock the keyboard?
You can use the keyboard button on the top right to block/unblock the keyboard. If you don't see the button, swipe from the left and choose "toggle appbar visibility"
![image](https://user-images.githubusercontent.com/12110344/87912178-31902e00-ca6d-11ea-8096-1d17a9cdeb1d.png)

**Comment by void00r** [comment]
Ohh I think it should be visible by default. Its confusing for new peoples especially normies.

**Comment by 92lleo** [comment]
The keyboard is unlocked and the appbar is visible by default. If it was diffrent for you, please check again (delete app data and start fresh). If the issue persists, please repoen this issue.
