### ISSUE TITLE
Resizable Running Activity

### ISSUE THREAD

**Issue by tastelessjolt** [92lleo/WhatsappWebToGo#33]
It'd be great if resizing the app in multi-app view would not restart the app everytime. Currently, it resizes but refreshes the content. I think this might be fixed with a few flags on the activity. 

Thanks in advance

**Comment by 92lleo** [comment]
Hi, 
thanks for the feedback. I'll look into it.

Best,
Leo

**Comment by 92lleo** [comment]
See release 1.6.3, it's up here on github now or on fdroid in 2-3 days, depending from what source you installed it

**Comment by tastelessjolt** [comment]
Thanks a lot! It works great now! :100:
