### ISSUE TITLE
1.6.4 f-droid 

### ISSUE THREAD

**Issue by VerixGH** [92lleo/WhatsappWebToGo#40]
When will the new version be available on f droid?

**Comment by 92lleo** [comment]
Usually it only takes one day. Fdroid looks like fdroid has not picked up the git tag yet, I'll check

**Comment by 92lleo** [comment]
Build was running on thursday morning: https://f-droid.org/wiki/page/io.kuenzler.whatsappwebtogo/lastbuild_33
It should be picked up by the store shortly

**Comment by 92lleo** [comment]
ref: https://gitlab.com/fdroid/fdroiddata/-/commit/4da6c71f003deea5283ce81f91462fbbff97cd56

**Comment by 92lleo** [comment]
There seems to be an issue with store entry indexing, nothing we can do on our side. You can always build from source yourself or use the apk in the release section here - but please keep in mind that they are signed diffrently, so you cant switch from one release channel to another (github/fdroid) without re-installing

**Comment by 92lleo** [comment]
https://f-droid.org/en/packages/io.kuenzler.whatsappwebtogo/
1.6.4 / 33 is available on fdroid now
