### ISSUE TITLE
purchase this poject

### ISSUE THREAD

**Issue by firebrain12** [92lleo/WhatsappWebToGo#44]
hi is it possible to purchase this project or can i get permission to use this project for commercial use without Mit license license policy?

**Comment by 92lleo** [comment]
Clarified by mail

**Comment by firebrain12** [comment]
Hey glad we can work together this is my first contribution to GitHub and
am still learning more about java feel free to make any changes to my
contribution got some other stuff am working on atm so time I don't have
but Al be contributing regular :)

BR
Markie
