### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by shawn1thompson** [92lleo/WhatsappWebToGo#47]
I'm not sure if I'm missing something, but I don't know how to login. There's a QR code I would normally scan with my phone, but the QR code is already on my phone screen.

**Comment by 92lleo** [comment]
This app is for use with a second phone. If you have whatsapp and whatsappWebToGo on the same phone, there is no real benefit, as it would use the same account.
-> install WhatsappWebToGo on another phone where you want to access your chats (like on whatsapp web on desktop)
-> open Whatsapp on your primary phone and scan the qr code from the other phone

**Comment by shawn1thompson** [comment]
Makes sense. Thanks.

**Comment by cellfdroid** [comment]
Well, technically it seems possible to use on same device as well. In case someone is tired of forced updates every 6 months or privacy policy popups.

If your device supports split screen put this app on top and whatsapp on bottom half. Then take screenshot and copy it to pc or other device. Using whatsapp in bottom half of screen scan qr code on pc screenshot.
