### ISSUE TITLE
login?

### ISSUE THREAD

**Issue by NSTAdventure** [92lleo/WhatsappWebToGo#51]
Whatsapp ask for QR scan how do i scan that tho?

**Comment by 92lleo** [comment]
See #47

**Comment by NSTAdventure** [comment]
Bruh  i guess this app literally useless on my devices I though i can login directly but thanks for your clarification

**Comment by NSTAdventure** [comment]
> It's only useful if you use it on another phone then the one where whatsapp is installed :) It's basically just web.whatsapp.com

Yeah  i know right thanks anyway and sorry if i offended you it's not my intention to
