### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by github838** [92lleo/WhatsappWebToGo#53]
Hi,
Someone threatened me that he will banned my number from WhatsApp and here we are 🙂💔
![image](https://user-images.githubusercontent.com/78624931/127728517-66d3c577-2e13-42a6-8739-7b2b34debebc.jpeg)
I don't know how he did this and I don't know how to protect myself from things like this

**Comment by 92lleo** [comment]
Hi,
first of all, thats not an issue from this app, so I'd really like to edit your title and description to highlight that.
Have you tried those steps: https://www.callbell.eu/en/whatsapp-business-number-blocked/ ? In any case you need to get in touch with WA support to find out what happened

**Comment by JustAnotherSupporter** [comment]
The issue were with whatsapp itself. Or rather with the installation method used on Aurora Store.
Since changing the installation method in Aurora Store from the "session installer" to the "native installer" in regards to WhatsApp itself there hasn't been any issues.

Thank you for your guidance!

**Comment by djoris** [comment]
my experience: I downloaded the WhatsApp APK from whatsapp.com and installed it in an Android emulator (Genymotion). I did a small configuration of that account there.
A few seconds after I linked WhatsappWebToGo, my account got blocked: "This account is not allowed to use WhatsApp due to spam."
