### ISSUE TITLE
Remove "Your Battery Status is Low" notification

### ISSUE THREAD

**Issue by darkenedcolossal** [92lleo/WhatsappWebToGo#56]
I have WhatsApp on the same phone on another account and WWTG always shows me the above notification.
Maybe it's just my case, but if more are affected you might want to fix that.

**Comment by 92lleo** [comment]
@darkenedcolossal  actually since I have my new phone, I get this notification constantly (not only on WWTG, but also on browser/desktop). Seems phone releated, I don't know a fix yet
