### ISSUE TITLE
App doesn't load setup screen on low-end Android 5.1 device

### ISSUE THREAD

**Issue by alessandro-cojp** [92lleo/WhatsappWebToGo#57]
I own a BRONDI smartphone (branded chinese OEM smartphone) that I'd like to use as a distraction free device with only WhatsApp Web to Go and a few other apps from F-Droid.

Problem is that the app is stuck on the first loading screen. The setup with the QR Code never appears. I tried version 1.6.4 up to 1.7.1

Here are the specs from the BRONDI smartphone:
CPU: Mediatek MT6580M
Cortex-A7 
RAM: 512MB
OS: Android 5.1

I also tried on another Android 5.1 device (Huawei GR3) and it works. There's any log file that I can attach?

**Comment by 92lleo** [comment]
Hi, sorry for the late answer. 
As you closed the issue, did you find a solution? My best guess is: Check if your webview provider (com.google.android.webview) is up to date.
