### ISSUE TITLE
App dosen't load QR Code screen    

### ISSUE THREAD

**Issue by ArunVicky001** [92lleo/WhatsappWebToGo#6]
Hi,
I've checked your source code it doesn't work, first time only it showing the QR code screen then always it showing the blank screen. After debugging the code I found that second time its loading https://www.whatsapp.com instead of https://web.whatsapp.com. Please fix it as soon as possible.

Thanks

**Comment by 92lleo** [comment]
Hi, make sure you have version 1.0.1 installed. The code here is not up to date yet.

**Comment by ArunVicky001** [comment]
Could you please update the source or tell the way to fix the issue 

Thanks.

**Comment by LilyIkhsan** [comment]
Hi, i can't find whatsapp web to go in the play store anymore :-(

Please give me the download link

**Comment by 92lleo** [comment]
Hi @LilyIkhsan 
The app got pulled from play store, you can find releases over at the [release tab ](https://github.com/92lleo/WhatsappWebToGo/releases)

@ArunVicky001 
Sources have been updated

**Comment by lisianeschwantes** [comment]
Olá Leonard, você avisará  quando o app estiver funcionando?  Obrigada!  Att, Lisiane
