### ISSUE TITLE
Downloaded file extension name is incorrect

### ISSUE THREAD

**Issue by fung04** [92lleo/WhatsappWebToGo#60]
I am not sure how the download work. My issue is when I try to download a Microsoft Word (.docx) extension name file it turn out become (.document) extension name file instead,

My solution to fix is change the (.document) back to (.docx) then I can view edit the document,

I am using the github latest release 1.7.1

![SmartSelect_20211111-222831_My Files](https://user-images.githubusercontent.com/86948094/141316511-4e483a23-9c2f-4ec3-ad2d-2f8aa40944f9.jpg)

Appreciate all the hard work you guys have made, is a really good application.

**Comment by 92lleo** [comment]
Hi, thanks for your report. Are you using the latest version?

"application/vnd.openxmlformats-officedocument.wordprocessingml.document" should be changed to docx , see https://github.com/92lleo/WhatsappWebToGo/blob/d4cc27d8cbe6e6ce8bc847728380bf4213092805/app/src/main/java/io/kuenzler/whatsappwebtogo/MimeTypes.java#L43

I'll see if I can reproduce this
