### ISSUE TITLE
Cannot send pdf document (send button not visible)

### ISSUE THREAD

**Issue by Premjit-Developer** [92lleo/WhatsappWebToGo#62]
![IMG_20211125_101221](https://user-images.githubusercontent.com/72644801/143380747-0a88835f-5f28-4d03-9e3c-dd3cb31b2983.jpg)

**Comment by 92lleo** [comment]
Hi, looks like this might be fixed with #52 
I'll try on my phone. What phone/screen ratio do you have?

**Comment by Premjit-Chowdhury** [comment]
> Hi, looks like this might be fixed with #52 I'll try on my phone. What phone/screen ratio do you have?

My phone name is Asus zenfone max pro m1 , 5.99 inch screen size with 18:9 full view , 2mm slim bezel.

**Comment by 92lleo** [comment]
#52 is not in any release yet, would be part of the next release. I'll build the version and do a full release, if that works for you then. eta: next few days

**Comment by Premjit-Chowdhury** [comment]
Yeap waiting 😄 , and thanks for replys.

**Comment by 92lleo** [comment]
#52 is in the latest release, but unfortunately it doesn't fix the cut out send button issue. Still investigating. why did you close the issue?

**Comment by Premjit-Chowdhury** [comment]
> #52 is in the latest release, but unfortunately it doesn't fix the cut out send button issue. Still investigating. why did you close the issue?

Ohh i thought you fixed it in previous update.

**Comment by 92lleo** [comment]
@Premjit-Chowdhury please create other issues for other problems or feature requests. 
regarding those two:
1) there is already a workaround used to get the download file, which unfortunately does not have the file name
2) Not easily possible as not provided by whatsapp web

**Comment by S7venLights** [comment]
A related comment, if keyboard is not blocked, the attachment menu doesn't work… It pops up and drops away immediately.
