### ISSUE TITLE
Whatsapp call support

### ISSUE THREAD

**Issue by Minionguyjpro** [92lleo/WhatsappWebToGo#65]
May you can make it possible to call? Maybe this is not possible because it's the web version, but maybe you can add some like css or html to make it possible to call with someone. (Sorry if i post many suggestions, i always like to give suggestions.)

**Comment by 92lleo** [comment]
Currently this app only supports what's possible in the web app, not the desktop app. Once calls are supported in the web app, they should work out of the box here.

**Comment by Minionguyjpro** [comment]
Yes, i understand that.
