### ISSUE TITLE
no page loads , not even login

### ISSUE THREAD

**Issue by teh404guy** [92lleo/WhatsappWebToGo#68]
Its probably a problem with the app not being compatible with bromite system webview

**Comment by 92lleo** [comment]
have you tried switching to android system webview / chrome webview just to try?
If you confirm that it's bromite webview, i'll look into it

**Comment by teh404guy** [comment]
Alr will try tomorrow

**Comment by teh404guy** [comment]
Nvm just updated webview tonight and it worked
