### ISSUE TITLE
One important feature request 

### ISSUE THREAD

**Issue by Premjit-Chowdhury** [92lleo/WhatsappWebToGo#70]
Just two feature requests to improve the user experience

1. After downloading any file (mainly pdf) the naming of that file is changed to ddmm.. format which some time irritates to find that file. So keep the real file name as sender send that file that would be beneficial.
2.  Make a radio button or check box to turn off auto downloading photos and videos. Because it consumes unwanted data.

**Comment by Minionguyjpro** [comment]
Why you closed it?

**Comment by Premjit-Chowdhury** [comment]
> Why you closed it?

Because by mistake i opened same issue two times
