### ISSUE TITLE
QR Code not scannable

### ISSUE THREAD

**Issue by aklecks** [92lleo/WhatsappWebToGo#74]
Since a week I haven't been able to scan a new code. Worked fine previously, now I switched back from LineageOS to MIUI.

**Comment by 92lleo** [comment]
Hi, thanks for your feedback. What exactly is the issue? Which phone are you on and which app version?
Is it maybe #61 or #71 ?

**Comment by aklecks** [comment]
Hi, thank you for the quick response and for your otherwise great app! My phone is a
 Xiaomi POCO F3 and i'm on MIUI 12.5.2 with no google play services. (Signature Spoofing is not up and running yet). 
 The App version is 1.7.2. 
 Before I was on LineageOS with some Signature Spoofing (some apps were spoofed some weren't) and on the same app version.
Unfortunately it is neither of the two issues. The QR code shows but it is not scannable from any phone, no matter if Multidevice enabled or disabled. I will look into whether it is my phone that is not capable of generating QR codes atm, (will try sharing a WiFi when I'm back home).

**Comment by aklecks** [comment]
Started working 3 days ago. All good now!

**Comment by 92lleo** [comment]
interesting :D do you know what changed?

**Comment by aklecks** [comment]
nope, no idea, did you release a new version?

**Comment by 92lleo** [comment]
no, still 1.7.2. I guess an android webview update oder wa web internal update fixed it - still strange.
Anyway, glad it works for you now!
