### ISSUE TITLE
Portrait Mode Scaling

### ISSUE THREAD

**Issue by 5ham5h33r** [92lleo/WhatsappWebToGo#75]
After the latest update 1.7.2, the app is unusable in portrait mode on Galaxy Tab S8 (and I assume same on other similar sized devices). The chat screen is entirely cropped off and only "WhatsApp Web" page (that's on the right of the screen in landscape mode is visible.
![Screenshot_20220307-233655_WhatsApp Web To Go](https://user-images.githubusercontent.com/20884345/157092464-99a5e24d-2dfc-48c5-b501-113ea14f29cf.jpg)

**Comment by 92lleo** [comment]
Thanks for your feedback. 
Known issue, best is to revert to previous version until the next update

**Comment by Abhijeetbyte** [comment]
Yeah version**1.7.0**is fine
