### ISSUE TITLE
Hide Logout button

### ISSUE THREAD

**Issue by bonzio** [92lleo/WhatsappWebToGo#76]
Hi,

I often accidentally logged out from the app whenever I want to refresh the messeges. Could you put the "Logout" button away from the main focus? The current placement is really close to the "Reload" button and it's also top above the other buttons. Which will lead to accidental logout. In addition to that, it gives impression that logout is the main feature of the menu.

![IMG_20220310_051037](https://user-images.githubusercontent.com/46659483/157536695-decd9398-3739-45d8-8711-a710fce03c2e.jpg)

I think logging out it's the least user want to do in an app. So following common UX conventional, putting logout button away from the main focus is a good idea. Like any other apps do.

Thanks in advance. I use your app a lot because MIUI has problem with default Whatsapp app.

**Comment by Minionguyjpro** [comment]
Also may add an option to use CSS to hide the ``logout`` button when WhatsApp is loading.

**Comment by 92lleo** [comment]
Hi, thanks for your feedback.
I'll move the Logout button further down in the next release and also add an "are you sure" popup to prevent unwanted logouts
