### ISSUE TITLE
Images selected from the Gallery are sent out as blank images

### ISSUE THREAD

**Issue by dadandalive** [92lleo/WhatsappWebToGo#79]
When sending out an image (by selecting the paperclip icon, and then the purple image circle shape icon, and then selecting an image from the gallery), it is sent out as a blank image. Already immediately after selecting the image and prior to sending it off, when shown inside the page where a text caption can be added (and other pictures could be added), it is shown as a blank rectangle. Some issue with the integration with Gallery I suppose (Gallery version 1.1.44, fwiw).

I'm using the latest version (1.7.2). All permissions are given, I'm using Android 6.0.1 on a Samsung Galaxy Note 4 (SM-N910F), and Android System WebView is up to date (version 99). 

I can send out pictures taken on the fly, and I can send them as documents. 

Here is an example screenshot of the intermediate page (after image selection and prior to image sending) (top section with the addressee name and avatar removed for privacy purposes):

![example](https://user-images.githubusercontent.com/37327758/162689622-e823a849-1c7b-4c90-8ed7-6a81024c6932.jpg)

**Comment by 92lleo** [comment]
@dadandalive are the pictures actually sent blank or is it just the preview that's blank?

**Comment by dadandalive** [comment]
Pictures are actually sent blank.

**Comment by dadandalive** [comment]
:frowning_face: Issue got 'automagically' resolved. I tried de-installing and reinstalling, but I can no longer reproduce the issue. No Webview update had been done meanwhile.

**Comment by 92lleo** [comment]
There are some issues that go away magically. Maybe it was a general whatsapp web problem that got resolved on whatsapp's side. Please reopen, if it occurs again
