### ISSUE TITLE
Publish on f-droid?

### ISSUE THREAD

**Issue by WPFilmmaker** [92lleo/WhatsappWebToGo#8]
Would you publish it on f-droid? AFAIK he guys at f-droid take care of everything, the devs of the app just have to assist them if something is not right with the build or if some non-free dependencies have to be replace. Don't know if you might have to rename it though (whatsapp must be registered?) but i think it is worth.

**Comment by 92lleo** [comment]
Good idea. After some messages with google play dev team it seams like there is no way to get it back to google play. I'll make it available on fdroid then.
Naming should not be a problem. If there are problems, I'll just follow the google play naming rules which was fine before

**Comment by WPFilmmaker** [comment]
Great! 

I think they use https://gitlab.com/fdroid/rfp/issues for submits, you need to tell them some specs of your app and a bot will automatically check if there are issues (proprietary tools used for buildings etc.) and let you know what to do.

@Izzy and @Bubu contribute to f-droid so perhaps they can help if you struggle.

**Comment by WPFilmmaker** [comment]
@92lleo Any news on this? I saw a new release, so maybe it is a good time to get into f-droid?

**Comment by 92lleo** [comment]
I checked the process, the main problem I see is with fdroid building the apk itself. This means the apk will be signed by fdroid, so updates from releases tab can't be done to the fdroid version and the other way round. Maybe i'll just stop releasing on github then. 
I'm on it

**Comment by WPFilmmaker** [comment]
I am not a dev so my opinion is worth 2 cents but I think you are right, afaik f-droid has an automatic building system so that f-droid users get updates automatically.

This means that non-f-droid and f-droid users will get updates differently yes, however I don't think this is a big issue as if you check: https://gitlab.com/fdroid/rfp/issues you will notice that most of apps are not released only on f-droid.

Most apps are present  on google play or github and f-droid so updating from different sources shouldn't be a problem, unless of course you want to stop doing the releasing process here and let f-droid do it for you :)

**Comment by cybera66** [comment]
Hi everyone. Whatever the solution, I think GitHub and FDroid are great! Fantastic that the project goes on :-)!

**Comment by 92lleo** [comment]
@WPFilmmaker Sorry, still didn't do it. If you want to start the progress, you're allowed to add an issue for this app. If you need anything, just comment here or write me a mail

**Comment by WPFilmmaker** [comment]
@92lleo What is the license of whatsappwebtogo? I couldn't find it anywhere and it is on of the requirements for submission.

**Comment by 92lleo** [comment]
@WPFilmmaker sorry for the delay, license is added (MIT)

**Comment by IzzySoft** [comment]
F-Droid maintainer here. Our bot just approved, and I prepared the metadata. You might wish to establish [Fastlane file structure](https://gitlab.com/snippets/1895688) to provide screenshots and maintain the app description yourself. Please let us know when you did so and have a tag covering fastlane.

**Comment by 92lleo** [comment]
Resubmitted with release 1.5.0, fastline file structure still on todo, keeping this open

**Comment by 92lleo** [comment]
Fastlane file structure will be tracked in #15 
request for packaging was successfully closed, closing this as soon as the app is in the store

**Comment by 92lleo** [comment]
@IzzySoft 
https://f-droid.org/wiki/page/io.kuenzler.whatsappwebtogo/lastbuild_26 
Is this due to the RC version of Build Tools (30.0.0 rc1), or is this a temporary access issue?

**Comment by IzzySoft** [comment]
I'm no packager so I hardly can tell, sorry.

**Comment by 92lleo** [comment]
One year later, it's finally done 🎉Thanks for your input! Proper store entry will be further traced in #15 
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/io.kuenzler.whatsappwebtogo)
