### ISSUE TITLE
Where are the downloads?

### ISSUE THREAD

**Issue by blogdemoi** [92lleo/WhatsappWebToGo#80]
Hi,

Could you tell me where are the files downloaded in my phone? I click on download but can't find the files.

Thank you.

**Comment by 92lleo** [comment]
Hi, 
do you have enabled the storage permission for the app? 
If yes, the download should open when clicking the download notification and be in your download

**Comment by blogdemoi** [comment]
> do you have enabled the storage permission for the app?

Hum, sorry for this. You were right I didn't enable the storage permission...

**Comment by 92lleo** [comment]
No problem. Actually the app should ask you to allow the storage permission, but thats not working currently
