### ISSUE TITLE
No web display

### ISSUE THREAD

**Issue by AstragoYT** [92lleo/WhatsappWebToGo#9]
Only a white Screen (Android Pie, Emui)

**Comment by 92lleo** [comment]
Hi, sorry for the late answer.
Have you tried to clear app cache & data?
Is the whole screen blank or do you see the navbar on top and can view the sidebar?

**Comment by priccis** [comment]
Change the user agent in line 72 of main. You can put the [same as your computer](https://duckduckgo.com/?q=what+is+my+user+agent&t=lm&ia=answer)

**Comment by 92lleo** [comment]
Please check https://github.com/92lleo/WhatsappWebToGo/releases/tag/v1.3.0
