### ISSUE TITLE
"Waiting for this message. Check your phone."

### ISSUE THREAD

**Issue by edent** [92lleo/WhatsappWebToGo#90]
I installed WebToGo and the official WhatsApp app. I scanned the WebToGo code into WhatsApp and connected them. Then I uninstalled the official WhatsApp client.

A friend sent me a message, and it displays this error;
![Waiting for this message. Check your phone.](https://user-images.githubusercontent.com/837136/195468725-dca540d7-9632-478e-82c9-1cc15cdfe4fa.png)

My reply was sent to the recipient and they were able to read it.

Do I need to keep the official app running in order to receive messages?

**Comment by 92lleo** [comment]
Hi, this is a general whatsapp web issue with multi device beta. whatsapp web / your phone need to exchange their keys for you to see the message in whatsapp web. This does not work immediately sometimes. If it still doesn't work, I'd suggest to re-connect whatsapp web.
Nothing I can do on the app side unfortunately
