### ISSUE TITLE
Cant open rare camera.

### ISSUE THREAD

**Issue by Brio96** [92lleo/WhatsappWebToGo#91]
Hi
Thanks for such a nice app really useful, was looking for something like this.
I just cant figure out how to enable rare camera to take photos and send someone. Whenever i click on camera button it opens selfie camera and theres seems to be no option to change it to rare.
So if its possible pls help.
Thanks for the app, really appreciate it.

**Comment by Brio96** [comment]
@92lleo 
Hi can u pls tell me how i can open rare camera. Its really important for me. Thanks

**Comment by 92lleo** [comment]
Hi @Brio96 
Whatsapp is loaded within androids webview. It's not possible to change webview's selected camera.

**Comment by Brio96** [comment]
@92lleo can there be any way around this problem like selecting photo option from the attachment button instead of camera option and then when the file chooser opens, there can be some sort of camera option which can open my main camera or some third party camera app so that then i can switch my rare camera.
Thanks

**Comment by 92lleo** [comment]
you can take a picture and select it from file chooser. no other options currently
