### ISSUE TITLE
Hi, Please check this.

### ISSUE THREAD

**Issue by AdityaPratapSinghR** [92lleo/WhatsappWebToGo#97]
This App has implemented Whatsapp web in such a way that it's like real Whatsapp. Here is the link:
https://play.google.com/store/apps/details?id=whatsapp.web.whatscan.whatsweb.qrscan

Is it possible to do it like this? This has a back button and send button and a separate chat section. 
Please tell me if it's possible like injecting some JS code. I tried to find it but I don't know much about JS.

One thing that I can think of is to scale the webview or like zoom in and out something on clicks like scroll to right to show chats when clicked on any element and on back press scroll to left. 

By the way, your app is great.

I am waiting for your reply. Thanks

**Comment by 92lleo** [comment]
Hi @AdityaPratapSinghR 
#81 is doing this, I just need to include it into next build

**Comment by AdityaPratapSinghR** [comment]
Hi, Thanks a lot.

**Comment by 92lleo** [comment]
closing this, please refer to #81 for updates
